name: Deploy via Cloud Build

env:
  PROJECT_ID: gcp-deploy-mock0106
  PROJECT_NUMBER: 694474841040
  WIF_PROVIDER: projects/694474841040/locations/global/workloadIdentityPools/github-pool/providers/github-provider
  DEPLOY_SA: cb-deployer@gcp-deploy-mock0106.iam.gserviceaccount.com

on:
  workflow_dispatch:
  push:
    branches: [main,master]


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Print context
        run: |
          echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}" 
          echo "GITHUB_REF=${GITHUB_REF}" 
          echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"
      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with: 
          # workload_identity_provider: projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          workload_identity_provider: ${{env.WIF_PROVIDER}}
          service_account: ${{env.DEPLOY_SA}}
      
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with: 
          project_id: ${{env.PROJECT_ID}}
      
      - name: Who am I
        run: |
          gcloud auth list

      - name: Submit Cloud Build
        run: |
          VERSION="$(date +%Y%m%d-%H%M)-${GITHUB_SHA::7}"
          echo "Using Tag_NAME=$VERSION"
          gcloud builds submit --config cloudbuild.yaml --substitutions=TAG_NAME="$VERSION" --verbosity=debug .
      
      - name: Get Cloud Run URL
        run: |
          URL=$(gcloud run services describe "${{vars.CLOUD_RUN_SERVICE}}" --region="asia-northeast1" --format='value(status.url)')
          echo "URL=$URL" >> "$GITHUB_ENV"
          
      - name: update Github About URL
        if: env.URL!=''
        env: 
          GH_TOKEN: ${{secrets.GH_ADMIN_TOKEN}}
        run: gh repo edit "${{github.repository}}" --homepage "${URL}"

